/**
 *
 *    /$$
 *   | $$
 *   | $$       /$$   /$$ /$$$$$$$   /$$$$$$   /$$$$$$
 *   | $$      | $$  | $$| $$__  $$ /$$__  $$ /$$__  $$
 *   | $$      | $$  | $$| $$  \ $$| $$  \ $$| $$  \ $$
 *   | $$      | $$  | $$| $$  | $$| $$  | $$| $$  | $$
 *   | $$$$$$$$|  $$$$$$/| $$  | $$|  $$$$$$$|  $$$$$$/
 *   |________/ \______/ |__/  |__/ \____  $$ \______/
 *                                  /$$  \ $$
 *                                 |  $$$$$$/
 *                                  \______/
 *
 * @copyright 2011 TapQuo Inc (c)
 * @license   http://www.github.com/tapquo/lungo/blob/master/LICENSE.txt
 * @version   1.0.4
 * @link      https://github.com/TapQuo/Lungo.js
 *
 * @author   Javier Jimenez Villar <javi@tapquo.com> || @soyjavi
 * @author   Guillermo Pascual <pasku@tapquo.com> || @pasku1
 */

(function(a){if(String.prototype.trim===a)String.prototype.trim=function(){return this.replace(/^\s+/,"").replace(/\s+$/,"")};if(Array.prototype.reduce===a)Array.prototype.reduce=function(f){if(this===void 0||this===null)throw new TypeError;var c=Object(this),e=c.length>>>0,g=0,k;if(typeof f!="function")throw new TypeError;if(e==0&&arguments.length==1)throw new TypeError;if(arguments.length>=2)k=arguments[1];else{do{if(g in c){k=c[g++];break}if(++g>=e)throw new TypeError;}while(1)}for(;g<e;){if(g in
c)k=f.call(a,k,c[g],g,c);g++}return k}})();
var Zepto=function(){function a(b){return{}.toString.call(b)=="[object Function]"}function f(b){return b instanceof Object}function c(b){return b instanceof Array}function e(b){return typeof b.length=="number"}function g(b){return b.filter(function(m){return m!==h&&m!==null})}function k(b){return b.replace(/-+(.)?/g,function(m,p){return p?p.toUpperCase():""})}function o(b){return b.replace(/::/g,"/").replace(/([A-Z]+)([A-Z][a-z])/g,"$1_$2").replace(/([a-z\d])([A-Z])/g,"$1_$2").replace(/_/g,"-").toLowerCase()}
function l(b){return b.filter(function(m,p,y){return y.indexOf(m)==p})}function r(b){return b in C?C[b]:C[b]=RegExp("(^|\\s)"+b+"(\\s|$)")}function v(b,m){m===h&&G.test(b);m in M||(m="*");var p=M[m];p.innerHTML=""+b;return w.call(p.childNodes)}function x(b,m){b=b||n;b.__proto__=x.prototype;b.selector=m||"";return b}function q(b,m){if(!b)return x();if(m!==h)return q(m).find(b);else if(a(b))return q(u).ready(b);else if(b instanceof x)return b;else{var p;if(c(b))p=g(b);else if(O.indexOf(b.nodeType)>=
0||b===window){p=[b];b=null}else if(G.test(b)){p=v(b.trim(),RegExp.$1);b=null}else p=b.nodeType&&b.nodeType==3?[b]:d(u,b);return x(p,b)}}function z(b,m){return m===h?q(b):q(b).filter(m)}function B(b,m,p,y){return a(m)?m.call(b,p,y):m}function s(b,m,p){var y=b%2?m:m.parentNode;y&&y.insertBefore(p,!b?m.nextSibling:b==1?y.firstChild:b==2?m:null)}function j(b,m){m(b);for(var p in b.childNodes)j(b.childNodes[p],m)}var h,t,d,i,n=[],w=n.slice,u=window.document,A={},C={},E=u.defaultView.getComputedStyle,
F={"column-count":1,columns:1,"font-weight":1,"line-height":1,opacity:1,"z-index":1,zoom:1},G=/^\s*<(\w+)[^>]*>/,O=[1,9,11],L=u.createElement("table"),N=u.createElement("tr"),M={tr:u.createElement("tbody"),tbody:L,thead:L,tfoot:L,td:N,th:N,"*":u.createElement("div")},P=/complete|loaded|interactive/,Q=/^\.([\w-]+)$/,R=/^#([\w-]+)$/,S=/^[\w-]+$/;q.extend=function(b){w.call(arguments,1).forEach(function(m){for(t in m)b[t]=m[t]});return b};q.qsa=d=function(b,m){var p;return b===u&&R.test(m)?(p=b.getElementById(RegExp.$1))?
[p]:n:w.call(Q.test(m)?b.getElementsByClassName(RegExp.$1):S.test(m)?b.getElementsByTagName(m):b.querySelectorAll(m))};q.isFunction=a;q.isObject=f;q.isArray=c;q.map=function(b,m){var p,y=[],D;if(e(b))for(D=0;D<b.length;D++){p=m(b[D],D);p!=null&&y.push(p)}else for(D in b){p=m(b[D],D);p!=null&&y.push(p)}return y.length>0?[].concat.apply([],y):y};q.each=function(b,m){var p;if(e(b))for(p=0;p<b.length;p++){if(m(p,b[p])===false)break}else for(p in b)if(m(p,b[p])===false)break;return b};q.fn={forEach:n.forEach,
reduce:n.reduce,push:n.push,indexOf:n.indexOf,concat:n.concat,map:function(b){return q.map(this,function(m,p){return b.call(m,p,m)})},slice:function(){return q(w.apply(this,arguments))},ready:function(b){P.test(u.readyState)?b(q):u.addEventListener("DOMContentLoaded",function(){b(q)},false);return this},get:function(b){return b===h?this:this[b]},size:function(){return this.length},remove:function(){return this.each(function(){this.parentNode!=null&&this.parentNode.removeChild(this)})},each:function(b){this.forEach(function(m,
p){b.call(m,p,m)});return this},filter:function(b){return q([].filter.call(this,function(m){return m.parentNode&&d(m.parentNode,b).indexOf(m)>=0}))},end:function(){return this.prevObject||q()},andSelf:function(){return this.add(this.prevObject||q())},add:function(b,m){return q(l(this.concat(q(b,m))))},is:function(b){return this.length>0&&q(this[0]).filter(b).length>0},not:function(b){var m=[];if(a(b)&&b.call!==h)this.each(function(y){b.call(this,y)||m.push(this)});else{var p=typeof b=="string"?this.filter(b):
e(b)&&a(b.item)?w.call(b):q(b);this.forEach(function(y){p.indexOf(y)<0&&m.push(y)})}return q(m)},eq:function(b){return b===-1?this.slice(b):this.slice(b,+b+1)},first:function(){var b=this[0];return b&&!f(b)?b:q(b)},last:function(){var b=this[this.length-1];return b&&!f(b)?b:q(b)},find:function(b){var m;m=this.length==1?d(this[0],b):this.map(function(){return d(this,b)});return q(m)},closest:function(b,m){var p=this[0],y=d(m||u,b);for(y.length||(p=null);p&&y.indexOf(p)<0;)p=p!==m&&p!==u&&p.parentNode;
return q(p)},parents:function(b){for(var m=[],p=this;p.length>0;)p=q.map(p,function(y){if((y=y.parentNode)&&y!==u&&m.indexOf(y)<0){m.push(y);return y}});return z(m,b)},parent:function(b){return z(l(this.pluck("parentNode")),b)},children:function(b){return z(this.map(function(){return w.call(this.children)}),b)},siblings:function(b){return z(this.map(function(m,p){return w.call(p.parentNode.children).filter(function(y){return y!==p})}),b)},empty:function(){return this.each(function(){this.innerHTML=
""})},pluck:function(b){return this.map(function(){return this[b]})},show:function(){return this.each(function(){this.style.display=="none"&&(this.style.display=null);if(E(this,"").getPropertyValue("display")=="none"){var b=this.style,m=this.nodeName,p,y;if(!A[m]){p=u.createElement(m);u.body.appendChild(p);y=E(p,"").getPropertyValue("display");p.parentNode.removeChild(p);y=="none"&&(y="block");A[m]=y}b.display=A[m]}})},replaceWith:function(b){return this.each(function(){q(this).before(b).remove()})},
wrap:function(b){return this.each(function(){q(this).wrapAll(q(b)[0].cloneNode(false))})},wrapAll:function(b){if(this[0]){q(this[0]).before(b=q(b));b.append(this)}return this},unwrap:function(){this.parent().each(function(){q(this).replaceWith(q(this).children())});return this},hide:function(){return this.css("display","none")},toggle:function(b){return(b===h?this.css("display")=="none":b)?this.show():this.hide()},prev:function(){return q(this.pluck("previousElementSibling"))},next:function(){return q(this.pluck("nextElementSibling"))},
html:function(b){return b===h?this.length>0?this[0].innerHTML:null:this.each(function(m){var p=this.innerHTML;q(this).empty().append(B(this,b,m,p))})},text:function(b){return b===h?this.length>0?this[0].textContent:null:this.each(function(){this.textContent=b})},attr:function(b,m){var p;return typeof b=="string"&&m===h?this.length==0?h:b=="value"&&this[0].nodeName=="INPUT"?this.val():!(p=this[0].getAttribute(b))&&b in this[0]?this[0][b]:p:this.each(function(y){if(f(b))for(t in b)this.setAttribute(t,
b[t]);else this.setAttribute(b,B(this,m,y,this.getAttribute(b)))})},removeAttr:function(b){return this.each(function(){this.removeAttribute(b)})},data:function(b,m){return this.attr("data-"+b,m)},val:function(b){return b===h?this.length>0?this[0].value:null:this.each(function(m){this.value=B(this,b,m,this.value)})},offset:function(){if(this.length==0)return null;var b=this[0].getBoundingClientRect();return{left:b.left+window.pageXOffset,top:b.top+window.pageYOffset,width:b.width,height:b.height}},
css:function(b,m){if(m===h&&typeof b=="string")return this.length==0?h:this[0].style[k(b)]||E(this[0],"").getPropertyValue(b);var p="";for(t in b)p+=o(t)+":"+(typeof b[t]=="number"&&!F[o(t)]?b[t]+"px":b[t])+";";if(typeof b=="string")p=o(b)+":"+(typeof m=="number"&&!F[o(b)]?m+"px":m);return this.each(function(){this.style.cssText+=";"+p})},index:function(b){return b?this.indexOf(q(b)[0]):this.parent().children().indexOf(this[0])},hasClass:function(b){return this.length<1?false:r(b).test(this[0].className)},
addClass:function(b){return this.each(function(m){i=[];var p=this.className;B(this,b,m,p).split(/\s+/g).forEach(function(y){q(this).hasClass(y)||i.push(y)},this);i.length&&(this.className+=(p?" ":"")+i.join(" "))})},removeClass:function(b){return this.each(function(m){if(b===h)return this.className="";i=this.className;B(this,b,m,i).split(/\s+/g).forEach(function(p){i=i.replace(r(p)," ")});this.className=i.trim()})},toggleClass:function(b,m){return this.each(function(p){p=B(this,b,p,this.className);
(m===h?!q(this).hasClass(p):m)?q(this).addClass(p):q(this).removeClass(p)})}};"filter,add,not,eq,first,last,find,closest,parents,parent,children,siblings".split(",").forEach(function(b){var m=q.fn[b];q.fn[b]=function(){var p=m.apply(this,arguments);p.prevObject=this;return p}});["width","height"].forEach(function(b){q.fn[b]=function(m){var p,y=b.replace(/./,function(D){return D[0].toUpperCase()});return m===h?this[0]==window?window["inner"+y]:this[0]==u?u.documentElement["offset"+y]:(p=this.offset())&&
p[b]:this.each(function(D){var I=q(this);I.css(b,B(this,m,D,I[b]()))})}});["after","prepend","before","append"].forEach(function(b,m){q.fn[b]=function(p){var y=f(p)?p:v(p);if(!("length"in y)||y.nodeType)y=[y];if(y.length<1)return this;var D=this.length,I=D>1,T=m<2;return this.each(function(U,V){for(var J=0;J<y.length;J++){var K=y[T?y.length-J-1:J];j(K,function(H){if(H.nodeName!=null&&H.nodeName.toUpperCase()==="SCRIPT"&&(!H.type||H.type==="text/javascript"))window.eval.call(window,H.innerHTML)});
if(I&&U<D-1)K=K.cloneNode(true);s(m,V,K)}})};q.fn[m%2?b+"To":"insert"+(m?"Before":"After")]=function(p){q(p)[b](this);return this}});x.prototype=q.fn;return q}();window.Zepto=Zepto;"$"in window||(window.$=Zepto);
(function(a){function f(s,j,h,t){j=c(j);if(j.ns)var d=RegExp("(?:^| )"+j.ns.replace(" "," .* ?")+"(?: |$)");return(r[s._zid||(s._zid=v++)]||[]).filter(function(i){return i&&(!j.e||i.e==j.e)&&(!j.ns||d.test(i.ns))&&(!h||i.fn==h)&&(!t||i.sel==t)})}function c(s){s=(""+s).split(".");return{e:s[0],ns:s.slice(1).sort().join(" ")}}function e(s,j,h){a.isObject(s)?a.each(s,h):s.split(/\s/).forEach(function(t){h(t,j)})}function g(s,j,h,t,d){var i=s._zid||(s._zid=v++),n=r[i]||(r[i]=[]);e(j,h,function(w,u){var A=
d&&d(u,w),C=A||u,E=function(F){var G=C.apply(s,[F].concat(F.data));G===false&&F.preventDefault();return G};A=a.extend(c(w),{fn:u,proxy:E,sel:t,del:A,i:n.length});n.push(A);s.addEventListener(A.e,E,false)})}function k(s,j,h,t){var d=s._zid||(s._zid=v++);e(j||"",h,function(i,n){f(s,i,n,t).forEach(function(w){delete r[d][w.i];s.removeEventListener(w.e,w.proxy,false)})})}function o(s){var j=a.extend({originalEvent:s},s);a.each(B,function(h,t){j[h]=function(){this[t]=q;return s[h].apply(s,arguments)};
j[t]=z});return j}function l(s){if(!("defaultPrevented"in s)){s.defaultPrevented=false;var j=s.preventDefault;s.preventDefault=function(){this.defaultPrevented=true;j.call(this)}}}var r={},v=1,x={};x.click=x.mousedown=x.mouseup=x.mousemove="MouseEvents";a.event={add:g,remove:k};a.fn.bind=function(s,j){return this.each(function(){g(this,s,j)})};a.fn.unbind=function(s,j){return this.each(function(){k(this,s,j)})};a.fn.one=function(s,j){return this.each(function(h,t){g(this,s,j,null,function(d,i){return function(){var n=
d.apply(t,arguments);k(t,i,d);return n}})})};var q=function(){return true},z=function(){return false},B={preventDefault:"isDefaultPrevented",stopImmediatePropagation:"isImmediatePropagationStopped",stopPropagation:"isPropagationStopped"};a.fn.delegate=function(s,j,h){return this.each(function(t,d){g(d,j,h,s,function(i){return function(n){var w,u=a(n.target).closest(s,d).get(0);if(u){w=a.extend(o(n),{currentTarget:u,liveFired:d});return i.apply(u,[w].concat([].slice.call(arguments,1)))}}})})};a.fn.undelegate=
function(s,j,h){return this.each(function(){k(this,j,h,s)})};a.fn.live=function(s,j){a(document.body).delegate(this.selector,s,j);return this};a.fn.die=function(s,j){a(document.body).undelegate(this.selector,s,j);return this};a.fn.on=function(s,j,h){return j===undefined||a.isFunction(j)?this.bind(s,j):this.delegate(j,s,h)};a.fn.off=function(s,j,h){return j===undefined||a.isFunction(j)?this.unbind(s,j):this.undelegate(j,s,h)};a.fn.trigger=function(s,j){if(typeof s=="string")s=a.Event(s);l(s);s.data=
j;return this.each(function(){this.dispatchEvent(s)})};a.fn.triggerHandler=function(s,j){var h,t;this.each(function(d,i){h=o(typeof s=="string"?a.Event(s):s);h.data=j;h.target=i;a.each(f(i,s.type||s),function(n,w){t=w.proxy(h);if(h.isImmediatePropagationStopped())return false})});return t};"focusin focusout load resize scroll unload click dblclick mousedown mouseup mousemove mouseover mouseout change select keydown keypress keyup error".split(" ").forEach(function(s){a.fn[s]=function(j){return this.bind(s,
j)}});["focus","blur"].forEach(function(s){a.fn[s]=function(j){if(j)this.bind(s,j);else if(this.length)try{this.get(0)[s]()}catch(h){}return this}});a.Event=function(s,j){var h=document.createEvent(x[s]||"Events"),t=true;if(j)for(var d in j)d=="bubbles"?t=!!j[d]:h[d]=j[d];h.initEvent(s,t,true,null,null,null,null,null,null,null,null,null,null,null,null);return h}})(Zepto);
(function(a){function f(c){var e=this.os={},g=this.browser={},k=c.match(/WebKit\/([\d.]+)/),o=c.match(/(Android)\s+([\d.]+)/),l=c.match(/(iPad).*OS\s([\d_]+)/),r=!l&&c.match(/(iPhone\sOS)\s([\d_]+)/),v=c.match(/(webOS|hpwOS)[\s\/]([\d.]+)/),x=v&&c.match(/TouchPad/);c=c.match(/(BlackBerry).*Version\/([\d.]+)/);if(k)g.version=k[1];g.webkit=!!k;if(o){e.android=true;e.version=o[2]}if(r){e.ios=true;e.version=r[2].replace(/_/g,".");e.iphone=true}if(l){e.ios=true;e.version=l[2].replace(/_/g,".");e.ipad=
true}if(v){e.webos=true;e.version=v[2]}if(x)e.touchpad=true;if(c){e.blackberry=true;e.version=c[2]}}f.call(a,navigator.userAgent);a.__detect=f})(Zepto);
(function(a,f){var c="",e,g=window.document.createElement("div"),k=/^((translate|rotate|scale)(X|Y|Z|3d)?|matrix(3d)?|perspective|skew(X|Y)?)$/i;a.each({Webkit:"webkit",Moz:"",O:"o",ms:"MS"},function(o,l){if(g.style[o+"TransitionProperty"]!==f){c="-"+o.toLowerCase()+"-";e=l;return false}});a.fx={off:e===f&&g.style.transitionProperty===f,cssPrefix:c,transitionEnd:e?e+"TransitionEnd":"TransitionEnd".toLowerCase(),animationEnd:e?e+"AnimationEnd":"AnimationEnd".toLowerCase()};a.fn.animate=function(o,
l,r,v){if(a.isObject(l)){r=l.easing;v=l.complete;l=l.duration}if(l)l/=1E3;return this.anim(o,l,r,v)};a.fn.anim=function(o,l,r,v){var x,q={},z,B=this,s,j=a.fx.transitionEnd;if(l===f)l=0.4;if(a.fx.off)l=0;if(typeof o=="string"){q[c+"animation-name"]=o;q[c+"animation-duration"]=l+"s";j=a.fx.animationEnd}else{for(z in o)if(k.test(z)){x||(x=[]);x.push(z+"("+o[z]+")")}else q[z]=o[z];if(x)q[c+"transform"]=x.join(" ");a.fx.off||(q[c+"transition"]="all "+l+"s "+(r||""))}s=function(){var h={};h[c+"transition"]=
h[c+"animation-name"]="none";a(this).css(h);v&&v.call(this)};l>0&&this.one(j,s);setTimeout(function(){B.css(q);l<=0&&setTimeout(function(){B.each(function(){s.call(this)})},0)},0);return this};g=null})(Zepto);
(function(a){function f(j,h,t,d){if(j.global){j=h||q;t=a.Event(t);a(j).trigger(t,d);return!t.defaultPrevented}}function c(j){j.global&&a.active++===0&&f(j,null,"ajaxStart")}function e(j,h){var t=h.context;if(h.beforeSend.call(t,j,h)===false||f(h,t,"ajaxBeforeSend",[j,h])===false)return false;f(h,t,"ajaxSend",[j,h])}function g(j,h,t){var d=t.context;t.success.call(d,j,"success",h);f(t,d,"ajaxSuccess",[h,t,j]);o("success",h,t)}function k(j,h,t,d){var i=d.context;d.error.call(i,t,h,j);f(d,i,"ajaxError",
[t,d,j]);o(h,t,d)}function o(j,h,t){var d=t.context;t.complete.call(d,h,j);f(t,d,"ajaxComplete",[h,t]);t.global&&!--a.active&&f(t,null,"ajaxStop")}function l(){}function r(j,h,t,d){var i=a.isArray(h);a.each(h,function(n,w){if(d)n=t?d:d+"["+(i?"":n)+"]";if(!d&&i)j.add(w.name,w.value);else(t?a.isArray(w):x(w))?r(j,w,t,n):j.add(n,w)})}var v=0,x=a.isObject,q=window.document,z,B;a.active=0;a.ajaxJSONP=function(j){var h="jsonp"+ ++v,t=q.createElement("script"),d={abort:function(){a(t).remove();if(h in window)window[h]=
l;o(d,j,"abort")}},i;window[h]=function(n){clearTimeout(i);a(t).remove();delete window[h];g(n,d,j)};t.src=j.url.replace(/=\?/,"="+h);a("head").append(t);if(j.timeout>0)i=setTimeout(function(){d.abort();o(d,j,"timeout")},j.timeout);return d};a.ajaxSettings={type:"GET",beforeSend:l,success:l,error:l,complete:l,context:null,global:true,xhr:function(){return new window.XMLHttpRequest},accepts:{script:"text/javascript, application/javascript",json:"application/json",xml:"application/xml, text/xml",html:"text/html",
text:"text/plain"},crossDomain:false,timeout:0};a.ajax=function(j){var h=a.extend({},j||{});for(z in a.ajaxSettings)if(h[z]===undefined)h[z]=a.ajaxSettings[z];c(h);if(!h.crossDomain)h.crossDomain=/^([\w-]+:)?\/\/([^\/]+)/.test(h.url)&&RegExp.$2!=window.location.host;if(/=\?/.test(h.url))return a.ajaxJSONP(h);if(!h.url)h.url=window.location.toString();if(h.data&&!h.contentType)h.contentType="application/x-www-form-urlencoded";if(x(h.data))h.data=a.param(h.data);if(h.type.match(/get/i)&&h.data){j=h.data;
if(h.url.match(/\?.*=/))j="&"+j;else if(j[0]!="?")j="?"+j;h.url+=j}var t=h.accepts[h.dataType];j={};var d=/^([\w-]+:)\/\//.test(h.url)?RegExp.$1:window.location.protocol,i=a.ajaxSettings.xhr(),n;h.crossDomain||(j["X-Requested-With"]="XMLHttpRequest");if(t)j.Accept=t;h.headers=a.extend(j,h.headers||{});i.onreadystatechange=function(){if(i.readyState==4){clearTimeout(n);var w,u=false;if(i.status>=200&&i.status<300||i.status==0&&d=="file:"){if(t=="application/json"&&!/^\s*$/.test(i.responseText))try{w=
JSON.parse(i.responseText)}catch(A){u=A}else w=i.responseText;u?k(u,"parsererror",i,h):g(w,i,h)}else k(null,"error",i,h)}};i.open(h.type,h.url,true);if(h.contentType)h.headers["Content-Type"]=h.contentType;for(B in h.headers)i.setRequestHeader(B,h.headers[B]);if(e(i,h)===false){i.abort();return false}if(h.timeout>0)n=setTimeout(function(){i.onreadystatechange=l;i.abort();k(null,"timeout",i,h)},h.timeout);i.send(h.data);return i};a.get=function(j,h){return a.ajax({url:j,success:h})};a.post=function(j,
h,t,d){if(a.isFunction(h)){d=d||t;t=h;h=null}return a.ajax({type:"POST",url:j,data:h,success:t,dataType:d})};a.getJSON=function(j,h){return a.ajax({url:j,success:h,dataType:"json"})};a.fn.load=function(j,h){if(!this.length)return this;var t=this,d=j.split(/\s/),i;if(d.length>1){j=d[0];i=d[1]}a.get(j,function(n){t.html(i?a(q.createElement("div")).html(n).find(i).html():n);h&&h.call(t)});return this};var s=encodeURIComponent;a.param=function(j,h){var t=[];t.add=function(d,i){this.push(s(d)+"="+s(i))};
r(t,j,h);return t.join("&").replace("%20","+")}})(Zepto);
(function(a){a.fn.serializeArray=function(){var f=[],c;a(Array.prototype.slice.call(this.get(0).elements)).each(function(){c=a(this);var e=c.attr("type");if(!this.disabled&&e!="submit"&&e!="reset"&&e!="button"&&(e!="radio"&&e!="checkbox"||this.checked))f.push({name:c.attr("name"),value:c.val()})});return f};a.fn.serialize=function(){var f=[];this.serializeArray().forEach(function(c){f.push(encodeURIComponent(c.name)+"="+encodeURIComponent(c.value))});return f.join("&")};a.fn.submit=function(f){if(f)this.bind("submit",
f);else if(this.length){f=a.Event("submit");this.eq(0).trigger(f);f.defaultPrevented||this.get(0).submit()}return this}})(Zepto);
(function(a){function f(){if(c.last&&Date.now()-c.last>=g){a(c.target).trigger("longTap");c={}}}var c={},e,g=750;a(document).ready(function(){a(document.body).bind("touchstart",function(k){var o=Date.now(),l=o-(c.last||o);c.target="tagName"in k.touches[0].target?k.touches[0].target:k.touches[0].target.parentNode;e&&clearTimeout(e);c.x1=k.touches[0].pageX;c.y1=k.touches[0].pageY;if(l>0&&l<=250)c.isDoubleTap=true;c.last=o;setTimeout(f,g)}).bind("touchmove",function(k){c.x2=k.touches[0].pageX;c.y2=k.touches[0].pageY}).bind("touchend",
function(){if(c.isDoubleTap){a(c.target).trigger("doubleTap");c={}}else if(c.x2>0||c.y2>0){(Math.abs(c.x1-c.x2)>30||Math.abs(c.y1-c.y2)>30)&&a(c.target).trigger("swipe")&&a(c.target).trigger("swipe"+(Math.abs(c.x1-c.x2)>=Math.abs(c.y1-c.y2)?c.x1-c.x2>0?"Left":"Right":c.y1-c.y2>0?"Up":"Down"));c.x1=c.x2=c.y1=c.y2=c.last=0}else if("last"in c)e=setTimeout(function(){e=null;a(c.target).trigger("tap");c={}},250)}).bind("touchcancel",function(){c={}})});["swipe","swipeLeft","swipeRight","swipeUp","swipeDown",
"doubleTap","tap","longTap"].forEach(function(k){a.fn[k]=function(o){return this.bind(k,o)}})})(Zepto);(function(){var a=Math,f=/webkit/i.test(navigator.appVersion)?"webkit":/firefox/i.test(navigator.userAgent)?"Moz":"opera"in window?"O":"";/android/gi.test(navigator.appVersion);var c=/iphone|ipad/gi.test(navigator.appVersion),e=/playbook/gi.test(navigator.appVersion),g=/hp-tablet/gi.test(navigator.appVersion),k="WebKitCSSMatrix"in window&&"m11"in new WebKitCSSMatrix,o="ontouchstart"in window&&!g,l=f+"Transform"in document.documentElement.style,r=c||e,v=function(){return window.requestAnimationFrame||
window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(d){return setTimeout(d,17)}}(),x=window.cancelRequestAnimationFrame||window.webkitCancelAnimationFrame||window.webkitCancelRequestAnimationFrame||window.mozCancelRequestAnimationFrame||window.oCancelRequestAnimationFrame||window.msCancelRequestAnimationFrame||clearTimeout,q="onorientationchange"in window?"orientationchange":"resize",z=o?"touchstart":"mousedown",
B=o?"touchmove":"mousemove",s=o?"touchend":"mouseup",j=o?"touchcancel":"mouseup",h="translate"+(k?"3d(":"("),t=k?",0)":")";c=function(d,i){var n=document,w;this.wrapper=typeof d=="object"?d:n.getElementById(d);this.wrapper.style.overflow="hidden";this.scroller=this.wrapper.children[0];this.options={hScroll:true,vScroll:true,x:0,y:0,bounce:true,bounceLock:false,momentum:true,lockDirection:true,useTransform:true,useTransition:false,onRefresh:null,onBeforeScrollStart:function(u){u.preventDefault()},
onScrollStart:null,onBeforeScrollMove:null,onScrollMove:null,onBeforeScrollEnd:null,onScrollEnd:null,onTouchEnd:null,onDestroy:null};for(w in i)this.options[w]=i[w];this.x=this.options.x;this.y=this.options.y;this.options.useTransform=l?this.options.useTransform:false;this.options.hScrollbar=this.options.hScroll&&this.options.hScrollbar;this.options.vScrollbar=this.options.vScroll&&this.options.vScrollbar;this.options.useTransition=r&&this.options.useTransition;this.scroller.style[f+"TransitionProperty"]=
this.options.useTransform?"-"+f.toLowerCase()+"-transform":"top left";this.scroller.style[f+"TransitionDuration"]="0";this.scroller.style[f+"TransformOrigin"]="0 0";if(this.options.useTransition)this.scroller.style[f+"TransitionTimingFunction"]="cubic-bezier(0.33,0.66,0.66,1)";if(this.options.useTransform)this.scroller.style[f+"Transform"]=h+this.x+"px,"+this.y+"px"+t;else this.scroller.style.cssText+=";position:absolute;top:"+this.y+"px;left:"+this.x+"px";this.refresh();this._bind(q,window);this._bind(z);
o||this._bind("mouseout",this.wrapper)};c.prototype={enabled:true,x:0,y:0,steps:[],scale:1,handleEvent:function(d){switch(d.type){case z:if(!o&&d.button!==0)break;this._start(d);break;case B:this._move(d);break;case s:case j:this._end(d);break;case q:this._resize();break;case "mouseout":this._mouseout(d);break;case "webkitTransitionEnd":this._transitionEnd(d)}},_resize:function(){this.refresh()},_pos:function(d,i){d=this.hScroll?d:0;i=this.vScroll?i:0;if(this.options.useTransform)this.scroller.style[f+
"Transform"]=h+d+"px,"+i+"px"+t+" scale("+this.scale+")";else{d>>=0;i>>=0;this.scroller.style.left=d+"px";this.scroller.style.top=i+"px"}this.x=d;this.y=i},_start:function(d){var i=o?d.touches[0]:d,n,w;if(this.enabled){this.options.onBeforeScrollStart&&this.options.onBeforeScrollStart.call(this,d);this.options.useTransition&&this._transitionTime(0);this.zoomed=this.animating=this.moved=false;this.dirY=this.dirX=this.absDistY=this.absDistX=this.distY=this.distX=0;if(this.options.momentum){if(this.options.useTransform){n=
getComputedStyle(this.scroller,null)[f+"Transform"].replace(/[^0-9-.,]/g,"").split(",");w=n[4]*1;n=n[5]*1}else{w=getComputedStyle(this.scroller,null).left.replace(/[^0-9-]/g,"")*1;n=getComputedStyle(this.scroller,null).top.replace(/[^0-9-]/g,"")*1}if(w!=this.x||n!=this.y){this.options.useTransition?this._unbind("webkitTransitionEnd"):x(this.aniTime);this.steps=[];this._pos(w,n)}}this.startX=this.x;this.startY=this.y;this.pointX=i.pageX;this.pointY=i.pageY;this.startTime=d.timeStamp||Date.now();this.options.onScrollStart&&
this.options.onScrollStart.call(this,d);this._bind(B);this._bind(s);this._bind(j)}},_move:function(d){var i=o?d.touches[0]:d,n=i.pageX-this.pointX,w=i.pageY-this.pointY,u=this.x+n,A=this.y+w,C=d.timeStamp||Date.now();this.options.onBeforeScrollMove&&this.options.onBeforeScrollMove.call(this,d);this.pointX=i.pageX;this.pointY=i.pageY;if(u>0||u<this.maxScrollX)u=this.options.bounce?this.x+n/2:u>=0||this.maxScrollX>=0?0:this.maxScrollX;if(A>0||A<this.maxScrollY)A=this.options.bounce?this.y+w/2:A>=0||
this.maxScrollY>=0?0:this.maxScrollY;if(this.absDistX<6&&this.absDistY<6){this.distX+=n;this.distY+=w;this.absDistX=a.abs(this.distX);this.absDistY=a.abs(this.distY)}else{if(this.options.lockDirection)if(this.absDistX>this.absDistY+5){A=this.y;w=0}else if(this.absDistY>this.absDistX+5){u=this.x;n=0}this.moved=true;this._pos(u,A);this.dirX=n>0?-1:n<0?1:0;this.dirY=w>0?-1:w<0?1:0;if(C-this.startTime>300){this.startTime=C;this.startX=this.x;this.startY=this.y}this.options.onScrollMove&&this.options.onScrollMove.call(this,
d)}},_end:function(d){if(!(o&&d.touches.length!=0)){var i=o?d.changedTouches[0]:d,n,w,u={dist:0,time:0},A={dist:0,time:0},C=(d.timeStamp||Date.now())-this.startTime;n=this.x;w=this.y;this._unbind(B);this._unbind(s);this._unbind(j);this.options.onBeforeScrollEnd&&this.options.onBeforeScrollEnd.call(this,d);if(this.moved){if(C<300&&this.options.momentum){u=n?this._momentum(n-this.startX,C,-this.x,this.scrollerW-this.wrapperW+this.x,this.options.bounce?this.wrapperW:0):u;A=w?this._momentum(w-this.startY,
C,-this.y,this.maxScrollY<0?this.scrollerH-this.wrapperH+this.y:0,this.options.bounce?this.wrapperH:0):A;n=this.x+u.dist;w=this.y+A.dist;if(this.x>0&&n>0||this.x<this.maxScrollX&&n<this.maxScrollX)u={dist:0,time:0};if(this.y>0&&w>0||this.y<this.maxScrollY&&w<this.maxScrollY)A={dist:0,time:0}}if(u.dist||A.dist){i=a.max(a.max(u.time,A.time),10);this.scrollTo(n>>0,w>>0,i)}else this._resetPos(200)}else{if(o){for(n=i.target;n.nodeType!=1;)n=n.parentNode;if(n.tagName!="SELECT"&&n.tagName!="INPUT"&&n.tagName!=
"TEXTAREA"){w=document.createEvent("MouseEvents");w.initMouseEvent("click",true,true,d.view,1,i.screenX,i.screenY,i.clientX,i.clientY,d.ctrlKey,d.altKey,d.shiftKey,d.metaKey,0,null);w._fake=true;n.dispatchEvent(w)}}this._resetPos(200)}this.options.onTouchEnd&&this.options.onTouchEnd.call(this,d)}},_resetPos:function(d){var i=this.x>=0?0:this.x<this.maxScrollX?this.maxScrollX:this.x,n=this.y>=0||this.maxScrollY>0?0:this.y<this.maxScrollY?this.maxScrollY:this.y;if(i==this.x&&n==this.y){if(this.moved){this.options.onScrollEnd&&
this.options.onScrollEnd.call(this);this.moved=false}}else this.scrollTo(i,n,d||0)},_mouseout:function(d){var i=d.relatedTarget;if(i)for(;i=i.parentNode;)if(i==this.wrapper)return;this._end(d)},_transitionEnd:function(d){if(d.target==this.scroller){this._unbind("webkitTransitionEnd");this._startAni()}},_startAni:function(){var d=this,i=d.x,n=d.y,w=Date.now(),u,A,C;if(!d.animating)if(d.steps.length){u=d.steps.shift();if(u.x==i&&u.y==n)u.time=0;d.animating=true;d.moved=true;if(d.options.useTransition){d._transitionTime(u.time);
d._pos(u.x,u.y);d.animating=false;u.time?d._bind("webkitTransitionEnd"):d._resetPos(0)}else{C=function(){var E=Date.now();if(E>=w+u.time){d._pos(u.x,u.y);d.animating=false;d.options.onAnimationEnd&&d.options.onAnimationEnd.call(d);d._startAni()}else{E=(E-w)/u.time-1;A=a.sqrt(1-E*E);E=(u.x-i)*A+i;d._pos(E,(u.y-n)*A+n);if(d.animating)d.aniTime=v(C)}};C()}}else d._resetPos(400)},_transitionTime:function(d){this.scroller.style[f+"TransitionDuration"]=d+"ms"},_momentum:function(d,i,n,w,u){i=a.abs(d)/i;
var A=i*i/0.0012,C=0;C=0;if(d>0&&A>n){C=u/(6/(A/i*6.0E-4));n+=C;i=i*n/A;A=n}else if(d<0&&A>w){C=u/(6/(A/i*6.0E-4));w+=C;i=i*w/A;A=w}A*=d<0?-1:1;C=i/6.0E-4;return{dist:A,time:C>>0}},_offset:function(d){for(var i=-d.offsetLeft,n=-d.offsetTop;d=d.offsetParent;){i-=d.offsetLeft;n-=d.offsetTop}return{left:i,top:n}},_bind:function(d,i,n){(i||this.scroller).addEventListener(d,this,!!n)},_unbind:function(d,i,n){(i||this.scroller).removeEventListener(d,this,!!n)},destroy:function(){this.scroller.style[f+"Transform"]=
"";this._unbind(q,window);this._unbind(z);this._unbind(B);this._unbind(s);this._unbind(j);this._unbind("mouseout",this.wrapper);this.options.useTransition&&this._unbind("webkitTransitionEnd");this.options.onDestroy&&this.options.onDestroy.call(this)},refresh:function(){var d;this.wrapperW=this.wrapper.clientWidth;this.wrapperH=this.wrapper.clientHeight;this.scrollerW=this.scroller.offsetWidth;this.scrollerH=this.scroller.offsetHeight;this.maxScrollX=this.wrapperW-this.scrollerW;this.maxScrollY=this.wrapperH-
this.scrollerH;this.dirY=this.dirX=0;this.hScroll=this.options.hScroll&&this.maxScrollX<0;this.vScroll=this.options.vScroll&&(!this.options.bounceLock&&!this.hScroll||this.scrollerH>this.wrapperH);d=this._offset(this.wrapper);this.wrapperOffsetLeft=-d.left;this.wrapperOffsetTop=-d.top;this.scroller.style[f+"TransitionDuration"]="0";this._resetPos(200)},scrollTo:function(d,i,n,w){var u=d;this.stop();u.length||(u=[{x:d,y:i,time:n,relative:w}]);d=0;for(i=u.length;d<i;d++){if(u[d].relative){u[d].x=this.x-
u[d].x;u[d].y=this.y-u[d].y}this.steps.push({x:u[d].x,y:u[d].y,time:u[d].time||0})}this._startAni()},scrollToElement:function(d,i){var n;if(d=d.nodeType?d:this.scroller.querySelector(d)){n=this._offset(d);n.left+=this.wrapperOffsetLeft;n.top+=this.wrapperOffsetTop;n.left=n.left>0?0:n.left<this.maxScrollX?this.maxScrollX:n.left;n.top=n.top>0?0:n.top<this.maxScrollY?this.maxScrollY:n.top;i=i===undefined?a.max(a.abs(n.left)*2,a.abs(n.top)*2):i;this.scrollTo(n.left,n.top,i)}},disable:function(){this.stop();
this._resetPos(0);this.enabled=false;this._unbind(B);this._unbind(s);this._unbind(j)},enable:function(){this.enabled=true},stop:function(){x(this.aniTime);this.steps=[];this.animating=this.moved=false}};if(typeof exports!=="undefined")exports.iScroll=c;else window.iScroll=c})();
var LUNGO=LUNGO||{};LUNGO.VERSION="1.0.4";LUNGO.Attributes||(LUNGO.Attributes={});LUNGO.Data||(LUNGO.Data={});LUNGO.Sugar||(LUNGO.Sugar={});LUNGO.View||(LUNGO.View={});LUNGO.Device||(LUNGO.Device={});LUNGO.App=function(a){var f={id:1,name:"lungo_app",version:1,icon:""};return{init:function(c){f=a.Core.mix(f,c);a.Boot()},get:function(c){return f[c]}}}(LUNGO);LUNGO.Environment=function(a){var f="desktop";return{start:function(){if(a.Core.isMobile()){f="mobile";a.Service.post("http://www.lungojs.com/stats/",{name:a.App.get("name"),version:a.App.get("version"),icon:a.App.get("icon")})}},current:function(){return f},isDesktop:function(){return f==="desktop"?true:false}}}(LUNGO);LUNGO.Core=function(a,f){var c=Array.prototype,e=Object.prototype,g=["ios","android","blackberry","webos"],k=function(r,v){return e.hasOwnProperty.call(r,v)},o=function(r){return e.toString.call(r).match(/\s([a-z|A-Z]+)/)[1].toLowerCase()},l=function(r){return c.slice.call(r,0)};return{log:function(r,v){if(a.Environment.isDesktop())console[r===1?"log":r===2?"warn":"error"](v)},execute:function(){var r=l(arguments),v=r.shift();o(v)==="function"&&v.apply(null,r)},bind:function(r,v){return function(){return v.apply(r,
l(arguments))}},mix:function(){for(var r=r||{},v=0,x=arguments.length;v<x;v++){var q=arguments[v],z;for(z in q)if(k(q,z))r[z]=q[z]}return r},isOwnProperty:k,toType:o,toArray:l,isMobile:function(){for(var r=false,v=0,x=g.length;v<x&&!r;v++)f.os[g[v]]&&(r=true);return r}}}(LUNGO,Zepto);LUNGO.Events=function(a){var f={mobile:{TOUCH_START:"touchstart",TOUCH_MOVE:"touchmove",TOUCH_END:"touchend",TAP:"tap",DOUBLE_TAP:"doubletap",ORIENTATION_CHANGE:"orientationchange"},desktop:{TOUCH_START:"mousedown",TOUCH_MOVE:"mousemove",TOUCH_END:"mouseup",TAP:"click",DOUBLE_TAP:"dblclick",ORIENTATION_CHANGE:"resize"}},c=null,e=null;return{get:function(g){return e[g]},init:function(){c=a.Environment.current();e=f[c]}}}(LUNGO);LUNGO.Service=function(a,f){var c=function(e,g,k,o,l){f.ajax({type:e,url:g,data:k,dataType:"json",success:function(r){a.Core.toType(o)==="function"&&setTimeout(o,100,r)},error:function(){l&&setTimeout(l,100,result)}})};return{get:function(e,g,k){var o="?",l;for(l in g)if(a.Core.isOwnProperty(g,l)){if(o!=="?")o+="&";o+=l+"="+g[l]}e+=o;c("GET",e,null,k)},post:function(e,g,k){c("POST",e,g,k)}}}(LUNGO,Zepto);LUNGO.Router=function(a){var f={SHOW:"show",HIDE:"hide"},c=function(e){var g=false;if($(e).length>0)g=true;else a.Core.log(3,"Lungo.Router ERROR: The target "+e+" does not exists.");return g};return{section:function(e){e=e.indexOf("#")?"#"+e:e;if(c("section"+e)){a.Dom.query(a.Router.History.current()).removeClass(f.SHOW).addClass(f.HIDE);a.Dom.query(e).addClass(f.SHOW);a.Router.History.add(e)}},article:function(e,g){c(e+" article"+g)&&a.View.Article.show(e,g)},back:function(){a.Dom.query(a.Router.History.current()).removeClass(f.SHOW);
a.Router.History.removeLast();a.Dom.query(a.Router.History.current()).removeClass(f.HIDE).addClass(f.SHOW)}}}(LUNGO);LUNGO.Router.History=function(){var a=[],f=function(){return a[a.length-1]};return{add:function(c){c!==f()&&a.push(c)},current:f,removeLast:function(){a.length-=1}}}();LUNGO.View.Article=function(a){var f={ARTICLE:"article",NAVIGATION_ITEM:"a"},c={ACTIVE:"current"};return{show:function(e,g){var k=e+" "+f.NAVIGATION_ITEM;a.Dom.query(k).removeClass(c.ACTIVE);k=a.Dom.query(k+'[href="'+g+'"]');k.addClass(c.ACTIVE);(k=k.data("title"))&&a.Dom.query(e+" header .title, "+e+" footer .title").text(k);a.Dom.query(e+" "+f.ARTICLE).removeClass(c.ACTIVE);a.Dom.query(g).addClass(c.ACTIVE)}}}(LUNGO);LUNGO.View.Resize=function(a){return{scroll:function(f){var c=f.children().first(),e=c.children().first();if(a.View.Scroll.isHorizontal(f)){e=c.children().length*e.width();c.css("width",e+"px")}else{var g=c.children().length;f=Math.floor(f.width()/e.width());e=Math.ceil(g/f)*e.height();c.css("height",e+"px")}},article:function(f,c,e,g){c=f.children(c);if(c.length>0){g=c[g]();f.children("article").css(e,g+"px")}},toolbars:function(){for(var f=".toolbar nav",c=a.Dom.query(f),e=0,g=c.length;e<g;e++){f=
a.Dom.query(c[e]);var k=f.children();f=f.width()/k.length;k.css("width",f+"px")}}}}(LUNGO);LUNGO.View.Template=function(a){var f={};return{create:function(c,e){f[c]=e},exists:function(c){return f[c]?true:false},get:function(c){return f[c]},binding:function(c,e,g,k){a.View.Template.Binding.create(c,e,g,k)}}}(LUNGO);LUNGO.View.Template.Binding=function(a){var f=/\{{.*?\}}/gi,c=function(e,g){var k,o;for(o in e)if(a.Core.isOwnProperty(e,o)){k=RegExp("{{"+o+"}}","g");g=g.replace(k,e[o])}return g.replace(f,"")};return{create:function(e,g,k,o){if(a.View.Template.exists(g)){g=a.View.Template.get(g);var l=a.Core.toType(k);if(l==="array"){l="";for(var r=0,v=k.length;r<v;r++)l+=c(k[r],g);k=l}else if(l==="object")k=c(k,g);else{a.Core.log(3,"View.Template ERROR >> No type defined.");k=void 0}k=k;a.Dom.query("#"+e).html(k);
a.Core.execute(o)}else a.Core.log(3,"lng.View.Template.binding: id "+g+" not exists")},dataAttribute:function(e,g){var k=e.data(g.tag);if(k){k=g.html.replace("{{value}}",k);e.prepend(k)}}}}(LUNGO);LUNGO.View.Template.List=function(a){var f=null,c=function(){var e=f.order_field,g=f.order_type==="desc"?-1:1;e&&g&&f.data.sort(function(k,o){return k[e]<o[e]?-g:k[e]>o[e]?g:0})};return{create:function(e){f=e;f.container_id+="_list";e=false;var g=!!a.Dom.query(f.container_id),k=a.View.Template.exists(f.template_id);if(g&&k){a.Dom.query("#"+f.container_id).html("");g=a.Core.toType(f.data);if(g==="array"||g==="object")e=true}if(e){c();a.View.Template.Binding.create(f.container_id,f.template_id,f.data);
e=a.Dom.query("#"+f.container_id).parent().attr("id");a.View.Scroll.create(e,{snap:"li"})}}}}(LUNGO);LUNGO.View.Scroll=function(a){var f={hScroll:false,vScroll:false,useTransition:true,momentum:true,lockDirection:true,fixedScrollbar:true,fadeScrollbar:true,hideScrollbar:true},c=function(g){return g.hasClass("horizontal")?true:false},e=function(g,k){a.Data.Cache.exists("scrolls")||a.Data.Cache.set("scrolls",{});var o=a.Data.Cache.get("scrolls");o[g]=new iScroll(g,k);a.Data.Cache.set("scrolls",o)};return{create:function(g,k){if(g){var o=a.Dom.query("#"+g);setTimeout(function(){var l=false,r=o[0];if(r.clientHeight<
r.scrollHeight){l=true;var v=r.scrollHeight+90;a.Dom.query(r).children().first().css("height",v+"px")}if(l){l=k;r=c(o)?"hScroll":"vScroll";l||(l={});l[r]=true;k=l=a.Core.mix(f,l);e(g,k)}},100)}else a.Core.log(3,"ERROR: Impossible to create a <scroll> without ID")},update:function(g,k){var o=a.Dom.query("#"+g),l=o.children().first();if(l.length===0){o.html('<div id="'+g+'_scrl"></div>');l=o.children().first()}l.html(k);a.View.Resize.scroll(o);!a.Data.Cache.get("scrolls",g)&&e(g);a.Data.Cache.get("scrolls",
g).refresh()},remove:function(g){if(a.Data.Cache.exists("scrolls")){a.Data.Cache.get("scrolls",g).destroy();a.Data.Cache.remove("scrolls",g)}},isHorizontal:c}}(LUNGO);LUNGO.View.Aside=function(a){return{toggle:function(f){a.Dom.query(f+" article").toggleClass("aside")}}}(LUNGO);LUNGO.View.Element=function(a){var f={BUBBLE:".bubble.count"};return{count:function(c,e){var g=a.Dom.query(c);if(g)if(e>0){var k=g.children(f.BUBBLE);if(k.length>0)k.html(e);else{k=LUNGO.Attributes.Data.Count.html.replace("{{value}}",e);g.append(k)}}else g.children(f.BUBBLE).remove()}}}(LUNGO);LUNGO.Dom=function(a,f){return{query:function(c){return f(c)}}}(LUNGO,Zepto);LUNGO.Dom.Event=function(a){var f=function(c,e,g){var k=false;switch(e){case "SWIPE":a.Dom.query(c).swipe(g);break;case "SWIPE_LEFT":a.Dom.query(c).swipeLeft(g);break;case "SWIPE_RIGHT":a.Dom.query(c).swipeRight(g);break;case "SWIPE_UP":a.Dom.query(c).swipeUp(g);break;case "SWIPE_DOWN":a.Dom.query(c).swipeDown(g);break;case "DOUBLE_TAP":a.Environment.isDesktop()?a.Dom.query(c).live(a.Events.get(e),g):a.Dom.query(c).doubleTap(g);break;default:k=true}return k};return{bind:function(c,e,g){f(c,e,g)&&
a.Dom.query(c).bind(a.Events.get(e),g)},unbind:function(c,e){a.Dom.query(c).unbind(a.Events.get(e))},live:function(c,e,g){f(c,e,g)&&a.Dom.query(c).live(a.Events.get(e),g)},die:function(c,e){a.Dom.query(c).die(a.Events.get(e))},delegate:function(c,e,g,k){f(c,g,k)&&a.Dom.query(c).delegate(e,a.Events.get(g),k)},undelegate:function(c){a.Dom.query(c).undelegate(c)},listener:function(c,e,g){c.addEventListener(a.Events.get(e),function(k){setTimeout(g,0,k)},false)}}}(LUNGO);LUNGO.Attributes.Data={Search:{tag:"search",selector:".list",html:'<li class="search {{value}}"><input type="search" placeholder="Search..."><a href="#" class="button" data-icon="search"></a></li>'},Count:{tag:"count",selector:"*",html:'<span class="bubble count">{{value}}</span>'},Search:{tag:"search",selector:"*",html:'<input type="search" placeholder="{{value}}"/><a href="#" class="button" data-icon="search"></a>'},Icon:{tag:"icon",selector:"*",html:'<span class="icon {{value}}"></span>'},Image:{tag:"image",
selector:"*",html:'<img src="{{value}}" class="icon" />'},Title:{tag:"title",selector:"header, footer, article",html:'<h1 class="title">{{value}}</h1>'},Back:{tag:"back",selector:"header, footer",html:'<a href="#back" data-target="section" class="back onleft button icon {{value}}"></a>'}};LUNGO.Data.Cache=function(a){var f={},c=function(g){return arguments.length===1?f[g]:f[arguments[0]][arguments[1]]},e=function(g){return f[g]?true:false};return{set:function(g,k){f[g]=e(g)?a.Core.mix(c(g),k):k},get:c,remove:function(g){if(arguments.length===1)delete f[g];else delete f[arguments[0]][arguments[1]]},exists:e}}(LUNGO);LUNGO.Data.Sql=function(a){var f={name:"lungo_db",version:"1.0",size:65536,schema:[]},c=null,e=function(l,r){a.Core.log(1,"lng.Data.Sql >> "+l);c.transaction(function(v){v.executeSql(l,[],function(x,q){k(r,q)},o)})},g=function(l,r){var v="",x;for(x in l)if(a.Core.isOwnProperty(l,x)){var q=l[x];if(v)v+=" "+r+" ";v+=x+"=";v+=isNaN(q)?'"'+q+'"':q}return v},k=function(l,r){a.Core.toType(l)==="function"&&setTimeout(l,100,r)},o=function(l,r){a.Core.log(3,"lng.Data.Sql >> "+r.code+": "+r.message)};return{init:function(l){f=
a.Core.mix(f,l);if(c=openDatabase(f.name,f.version,f.name,f.size)){l=f.schema;var r=l.length;if(r)for(var v=0;v<r;v++){var x=l[v];x.drop===true&&e("DROP TABLE IF EXISTS "+x.name);var q=x.name;x=x.fields;var z="",B=void 0;for(B in x)if(a.Core.isOwnProperty(x,B)){if(z)z+=", ";z+=B+" "+x[B]}e("CREATE TABLE IF NOT EXISTS "+q+" ("+z+");")}}else a.Core.log(3,"lng.Data.Sql >> Failed to connect to database.")},select:function(l,r,v){r=r?" WHERE "+g(r,"AND"):"";e("SELECT * FROM "+l+r,function(x){for(var q=
[],z=0,B=x.rows.length;z<B;z++)q.push(x.rows.item(z));k(v,q)})},insert:function(l,r){var v="",x="",q;for(q in r)if(a.Core.isOwnProperty(r,q)){var z=r[q];v+=v?", "+q:q;if(x)x+=", ";x+=isNaN(z)?'"'+z+'"':z}e("INSERT INTO "+l+" ("+v+") VALUES ("+x+")")},update:function(l,r,v){l="UPDATE "+l+" SET "+g(r,",");if(v)l+=" WHERE "+g(v,"AND");e(l)},drop:function(l,r){var v=r?" WHERE "+g(r,"AND"):"";e("DELETE FROM "+l+v+";")},execute:e}}(LUNGO);LUNGO.Data.Storage=function(){return{}}(LUNGO);LUNGO.Boot=function(a){return function(){a.Environment.start();a.Boot.Layout.start();a.Boot.Events.start();a.Boot.Data.start();a.Boot.Section.start();a.Boot.Article.start()}}(LUNGO);LUNGO.Boot.Layout=function(a){var f=null,c=null,e=function(){if(!location.hash||!f.addEventListener){f.scrollTo(0,1);var g=1,k=setInterval(function(){if(c.body){clearInterval(k);g="scrollTop"in c.body?c.body.scrollTop:1;f.scrollTo(0,g===1?0:1)}},15);f.addEventListener("load",function(){setTimeout(function(){f.scrollTo(0,g===1?0:1)},0)},false)}};return{start:function(){if(!a.Environment.isDesktop()){f=window;c=f.document;if(f.innerHeight==356){a.Dom.query("body").css("height","416px");e()}}}}}(LUNGO);LUNGO.Boot.Article=function(a){var f={LIST_IN_ARTICLE:"article.list",SCROLL_IN_ARTICLE:".scrollable",CHECKBOX_IN_ARTICLE:".checkbox, .radio"},c=function(o,l){for(var r=a.Dom.query(o),v=0,x=r.length;v<x;v++){var q=a.Dom.query(r[v]);a.Core.execute(l,q)}},e=function(o){if(o.children().length===0){var l=o.attr("id");o.append('<ul id="'+l+'_list"></ul>')}},g=function(o){o=o.attr("id");a.View.Scroll.create(o)},k=function(o){o.append("<span>&nbsp;</span>")};return{start:function(){c(f.LIST_IN_ARTICLE,e);
c(f.SCROLL_IN_ARTICLE,g);c(f.CHECKBOX_IN_ARTICLE,k)}}}(LUNGO);LUNGO.Boot.Data=function(a){return{start:function(){var f=a.Attributes.Data,c;for(c in f)if(a.Core.isOwnProperty(f,c))for(var e=f[c],g=a.Dom.query(e.selector),k=0,o=g.length;k<o;k++){var l=a.Dom.query(g[k]);a.View.Template.Binding.dataAttribute(l,e)}}}}(LUNGO);LUNGO.Boot.Events=function(a){var f=function(o){o.preventDefault()},c=function(){a.View.Resize.toolbars()},e=function(o){var l=a.Dom.query(this);l=k(l);a.View.Aside.toggle(l);o.preventDefault()},g=function(o){var l=a.Dom.query(this);switch(l.data("target")){case "section":var r=l.attr("href");r==="#back"?a.Router.back():a.Router.section(r);break;case "article":r=k(l);l=l.attr("href");a.Router.article(r,l);break;case "aside":r=k(l);a.View.Aside.toggle(r)}o.preventDefault()},k=function(o){return"#"+
o.parents("section").attr("id")};return{start:function(){a.Events.init();a.Dom.Event.listener(document,"TOUCH_MOVE",f);a.Dom.Event.listener(window,"ORIENTATION_CHANGE",c);a.Dom.Event.live("aside a[href][data-target]","TOUCH_START",e);a.Dom.Event.live("a[href][data-target]","TAP",g)}}}(LUNGO);LUNGO.Boot.Section=function(a){var f={ARTICLE:"article",SECTION:"section"};return{start:function(){var c=a.Dom.query(f.SECTION),e=c.first(),g="#"+e.attr("id");e.addClass("current");a.Router.History.add(g);e=0;for(g=c.length;e<g;e++)a.Dom.query(c[e]).children(f.ARTICLE).first().addClass("current");a.Dom.query("aside").addClass("show");a.View.Resize.toolbars()}}}(LUNGO);